let g:coc_global_extensions = [
      \ 'coc-css',
      \ 'coc-diagnostic',
      \ 'coc-eslint',
      \ 'coc-go',
      \ 'coc-highlight',
      \ 'coc-jest',
      \ 'coc-json',
      \ 'coc-neosnippet',
      \ 'coc-phpls',
      \ 'coc-prettier',
      \ 'coc-solargraph',
      \ 'coc-tsserver',
      \ 'coc-vetur',
      \ 'coc-cfn-lint',
      \ ]
