[[plugins]] # プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]] # ツリービュー表示
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/settings/plugins/nerdtree.rc.vim
'''

[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'

[[plugins]] # Emmet導入
repo = 'mattn/emmet-vim'
hook_add = '''
  source ~/.config/nvim/settings/plugins/emmet-vim.rc.vim
'''

[[plugins]] # コメントアウトショートカット導入
repo = 'tomtom/tcomment_vim'

[[plugins]] # ステータスライン表示
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.config/nvim/settings/plugins/vim-airline.rc.vim
'''

[[plugins]] # ステータスライン装飾
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ウィンドウサイズ変更用プラグイン
repo = 'simeji/winresizer'
hook_add = '''
  source ~/.config/nvim/settings/plugins/winresizer.rc.vim
'''

[[plugins]] # カラーテーブルを表示する
repo = 'guns/xterm-color-table.vim'

[[plugins]] # JavaScriptES6のシンタックス
repo = 'othree/yajs.vim'

[[plugins]] # vim上からgitコマンドを使えるプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] # カッコやHTMLタグなどの挿入、削除、置換プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # rails用プラグイン
repo = 'tpope/vim-rails'

[[plugins]] # vim help日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # インデントを可視化
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  source ~/.config/nvim/settings/plugins/vim-indent-guides.rc.vim
'''

[[plugins]] # nerdtreeにアイコン表示
repo = 'ryanoasis/vim-devicons'

[[plugins]] # 末尾の空白可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # gitで管理してる変更された箇所を行番号横に表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/settings/plugins/vim-gitgutter.rc.vim
'''

[[plugins]] # surround.vimなどの変更を.で繰り返し可能にする
repo = 'tpope/vim-repeat'

# [[plugins]] # スクロールを滑らかに
# repo = 'yuttie/comfortable-motion.vim'
# hook_add = '''
#   source ~/.config/nvim/settings/plugins/comfortable-motion.rc.vim
# '''

[[plugins]] # coffeescriptシンタックス
repo = 'kchmck/vim-coffee-script'

[[plugins]] # gundoグラフ可視化
repo = 'sjl/gundo.vim'
hook_add = '''
  source ~/.config/nvim/settings/plugins/gundo.rc.vim
'''

[[plugins]] # tomlシンタックス
repo = 'cespare/vim-toml'

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

[[plugins]] # Vue.jsシンタックス
repo = 'posva/vim-vue'
hook_add = '''
  source ~/.config/nvim/settings/plugins/vim-vue.rc.vim
'''

[[plugins]] # PHPのbladeファイル対応
repo = 'jwalton512/vim-blade'

[[plugins]] # fzfプラグイン
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/settings/plugins/fzf.rc.vim
'''

[[plugins]] # fzf本体
repo = '/usr/local/opt/fzf'

[[plugins]] # LSPクライアントパッケージマネージャー
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  source ~/.config/nvim/settings/plugins/coc.rc/init.vim
'''

[[plugins]] # typescriptシンタックス
repo = 'leafgarland/typescript-vim'

[[plugins]] # jsxシンタックス
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]] # tsxシンタックス
repo = 'ianks/vim-tsx'

[[plugins]] # スニペット定義
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # カラースキーム
repo = 'jonathanfilip/vim-lucius'

[[plugins]] # カラースキーム
repo = 'jdkanani/vim-material-theme'

[[plugins]] # 諸々機能拡張
repo = 'Shougo/unite.vim'

[[plugins]] # カラースキーム選択
repo = 'ujihisa/unite-colorscheme'
hook_add = '''
  source ~/.config/nvim/settings/plugins/unite-colorscheme.rc.vim
'''

[[plugins]] # カラースキーム
repo = 'gosukiwi/vim-atom-dark'

[[plugins]] # 閉じ括弧補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # ruby閉じend補完
repo = 'tpope/vim-endwise'

[[plugins]] # golang
repo = 'fatih/vim-go'

[[plugins]] # 禅モード
repo = 'junegunn/goyo.vim'

