[[plugins]] # スニペットエンジン
repo = 'Shougo/neosnippet'
hook_source = '''
  source ~/.config/nvim/settings/plugins/neosnippet.rc.d/init.vim
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
