[[plugins]] # Emmet導入
repo = 'mattn/emmet-vim'
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/emmet-vim.rc.vim'
'''
on_ft = ['html', 'eruby', 'javascriptreact', 'tsx', 'php', 'vue']

[[plugins]] # JavaScriptES6のシンタックス
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'vue', 'javascriptreact']

[[plugins]] # coffeescriptシンタックス
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]] # tomlシンタックス
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] # Vue.jsシンタックス
repo = 'posva/vim-vue'
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-vue.rc.vim'
'''
on_ft = ['vue']

[[plugins]] # PHPのbladeファイル対応
repo = 'jwalton512/vim-blade'
on_ft = ['blade']

[[plugins]] # typescriptシンタックス
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'tsx']

[[plugins]] # jsxシンタックス
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascriptreact', 'tsx']

[[plugins]] # tsxシンタックス
repo = 'ianks/vim-tsx'
on_ft = ['tsx']

# [[plugins]] # golang
# repo = 'fatih/vim-go'
# on_ft = ['go']

[[plugins]] # Xdebugとの連携プラグイン
repo = 'joonty/vdebug'
on_ft = ['php']
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vdebug.rc.vim'
'''

[[plugins]] # markkdownプレビュープラグイン
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app & yarn install"'
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/markdown-preview.rc.vim'
'''

[[plugins]] # Terraformシンタックス・コマンド
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

[[plugins]] # Golang formatter
repo = 'mattn/vim-goimports'
on_ft = ['go']

[[plugins]] # Protcol Buffers Syntax
repo = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]] # Dart
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/dart-vim-plugin.rc.vim'
'''

[[plugins]] # Flutter
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_source = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-flutter.rc.vim'
'''

# [[plugins]] # Scala LSP Client (coc-metals is deprecated)
# repo = 'scalameta/nvim-metals'
# on_ft = ['scala']
# hook_source = '''
#   execute 'source' g:ROOT_DIR . '/settings/plugins/nvim-metals.rc.vim'
# '''
# depends = ['plenary.nvim']

