[[plugins]] # プラグイン管理
repo = 'Shougo/dein.vim'

# [[plugins]] # ツリービュー表示
# repo = 'scrooloose/nerdtree'
# hook_add = '''
#   execute 'source' g:ROOT_DIR . '/settings/plugins/nerdtree.rc.vim'
# '''

[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'

[[plugins]] # コメントアウトショートカット導入
repo = 'tomtom/tcomment_vim'

[[plugins]] # ステータスライン表示
repo = 'vim-airline/vim-airline'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-airline.rc.vim'
'''

[[plugins]] # ステータスライン装飾
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ウィンドウサイズ変更用プラグイン
repo = 'simeji/winresizer'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/winresizer.rc.vim'
'''

[[plugins]] # vim上からgitコマンドを使えるプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] # カッコやHTMLタグなどの挿入、削除、置換プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # rails用プラグイン
repo = 'tpope/vim-rails'

[[plugins]] # vim help日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # インデントを可視化
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-indent-guides.rc.vim'
'''

[[plugins]] # アイコン
repo = 'ryanoasis/vim-devicons'

[[plugins]] # defxアイコン
repo = 'kristijanhusak/defx-icons'

[[plugins]] # defx Git
repo = 'kristijanhusak/defx-git'

[[plugins]] # deviconsにカラーをつける
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-nerdtree-syntax-highlight.rc.vim'
'''

[[plugins]] # gitで管理してる変更された箇所を行番号横に表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-gitgutter.rc.vim'
'''

[[plugins]] # surround.vimなどの変更を.で繰り返し可能にする
repo = 'tpope/vim-repeat'

# [[plugins]] # スクロールを滑らかに
# repo = 'yuttie/comfortable-motion.vim'
# hook_add = '''
#   execute 'source' g:ROOT_DIR . '/settings/plugins/comfortable-motion.rc.vim'
# '''

[[plugins]] # gundoグラフ可視化
repo = 'sjl/gundo.vim'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/gundo.rc.vim'
'''

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

[[plugins]] # fzfプラグイン
repo = 'junegunn/fzf.vim'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/fzf.rc.vim'
'''

[[plugins]] # fzf本体
repo = '/usr/local/opt/fzf'

[[plugins]] # LSPクライアントパッケージマネージャー
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/coc.rc.d/init.vim'
  execute 'source' g:ROOT_DIR . '/settings/plugins/coc.rc.d/extensions.vim'
'''

[[plugins]] # スニペット定義
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # カラースキーム
repo = 'jonathanfilip/vim-lucius'

[[plugins]] # カラースキーム
repo = 'jdkanani/vim-material-theme'

[[plugins]] # 諸々機能拡張
repo = 'Shougo/unite.vim'

[[plugins]] # カラースキーム選択
repo = 'ujihisa/unite-colorscheme'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/unite-colorscheme.rc.vim'
'''

[[plugins]] # カラースキーム
repo = 'gosukiwi/vim-atom-dark'

[[plugins]] # 閉じ括弧補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # ruby閉じend補完
repo = 'tpope/vim-endwise'

[[plugins]] # 禅モード
repo = 'junegunn/goyo.vim'

[[plugins]] # カラースキーム
repo = 'arcticicestudio/nord-vim'

[[plugins]] # 整列
repo = 'junegunn/vim-easy-align'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-easy-align.rc.vim'
'''

[[plugins]] # yank可視化
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-highlightedyank.rc.vim'
'''

[[plugins]] # ファイラー
repo = 'Shougo/defx.nvim'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/defx.rc.vim'
'''

[[plugins]] # GraphQL syntax
repo = 'jparise/vim-graphql'
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vim-graphql.rc.vim'
'''

[[plugins]] # デバッガー
repo = "puremourning/vimspector"
build = "./install_gadget.py --basedir $HOME/.config/nvim/settings/plugins/vimspector.rc.d"
hook_add = '''
  execute 'source' g:ROOT_DIR . '/settings/plugins/vimspector.rc.d/init.vim'
'''

[[plugins]] # カラースキーム
repo = 'w0ng/vim-hybrid'
# hook_add = '''
#   execute 'source' g:ROOT_DIR . '/settings/plugins/vim-graphql.rc.vim'
# '''

