[[plugins]] # プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]] # ツリービュー表示
repo = 'scrooloose/nerdtree'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/nerdtree.rc.vim'
'''

[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'

[[plugins]] # コメントアウトショートカット導入
repo = 'tomtom/tcomment_vim'

[[plugins]] # ステータスライン表示
repo = 'vim-airline/vim-airline'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/vim-airline.rc.vim'
'''

[[plugins]] # ステータスライン装飾
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ウィンドウサイズ変更用プラグイン
repo = 'simeji/winresizer'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/winresizer.rc.vim'
'''

[[plugins]] # vim上からgitコマンドを使えるプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] # カッコやHTMLタグなどの挿入、削除、置換プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # rails用プラグイン
repo = 'tpope/vim-rails'

[[plugins]] # vim help日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # インデントを可視化
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/vim-indent-guides.rc.vim'
'''

[[plugins]] # nerdtreeにアイコン表示
repo = 'ryanoasis/vim-devicons'

[[plugins]] # deviconsにカラーをつける
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]] # 末尾の空白可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # gitで管理してる変更された箇所を行番号横に表示
repo = 'airblade/vim-gitgutter'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/vim-gitgutter.rc.vim'
'''

[[plugins]] # surround.vimなどの変更を.で繰り返し可能にする
repo = 'tpope/vim-repeat'

# [[plugins]] # スクロールを滑らかに
# repo = 'yuttie/comfortable-motion.vim'
# hook_add = '''
#   execute 'source ' . g:root_dir . '/settings/plugins/comfortable-motion.rc.vim'
# '''

[[plugins]] # gundoグラフ可視化
repo = 'sjl/gundo.vim'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/gundo.rc.vim'
'''

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

[[plugins]] # fzfプラグイン
repo = 'junegunn/fzf.vim'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/fzf.rc.vim'
'''

[[plugins]] # fzf本体
repo = '/usr/local/opt/fzf'

[[plugins]] # LSPクライアントパッケージマネージャー
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/coc.rc.d/init.vim'
'''

[[plugins]] # スニペット定義
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # カラースキーム
repo = 'jonathanfilip/vim-lucius'

[[plugins]] # カラースキーム
repo = 'jdkanani/vim-material-theme'

[[plugins]] # 諸々機能拡張
repo = 'Shougo/unite.vim'

[[plugins]] # カラースキーム選択
repo = 'ujihisa/unite-colorscheme'
hook_add = '''
  execute 'source ' . g:root_dir . '/settings/plugins/unite-colorscheme.rc.vim'
'''

[[plugins]] # カラースキーム
repo = 'gosukiwi/vim-atom-dark'

[[plugins]] # 閉じ括弧補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # ruby閉じend補完
repo = 'tpope/vim-endwise'

[[plugins]] # 禅モード
repo = 'junegunn/goyo.vim'

[[plugins]] # カラースキーム
repo = 'arcticicestudio/nord-vim'

