[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ツリービュー表示
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:NERDTreeDirArrowExpandable = '▸'
  let g:NERDTreeDirArrowCollapsible = '▾'
  nnoremap <C-n> :<C-u>NERDTreeToggle<CR><C-l>
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'

[[plugins]] # 閉じカッコ保管
repo = 'cohama/lexima.vim'
hook_add = '''
  let g:user_emmet_leader_key = '<C-j>'
'''
[[plugins]] # Emmet導入
repo = 'mattn/emmet-vim'

[[plugins]] # コメントアウトショートカット導入
repo = 'tomtom/tcomment_vim'

[[plugins]] # ステータスライン表示
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'bubblegum'
  set laststatus=2
  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#wordcount#enabled = 0
  let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
  let g:airline_section_c = '%t'
  let g:airline_section_x = '%{&filetype}'
  let g:airline_section_z = '%3l:%2v %{airline#extensions#ale#get_warning()} %{airline#extensions#ale#get_error()}'
  let g:airline#extensions#ale#error_symbol = ' '
  let g:airline#extensions#ale#warning_symbol = ' '
  let g:airline#extensions#default#section_truncate_width = {}
  let g:airline#extensions#whitespace#enabled = 1
  nmap <C-e> <Plug>AirlineSelectPrevTab
  nmap <C-y> <Plug>AirlineSelectNextTab
  nnoremap <C-d> :bd<CR>
'''

[[plugins]] # ステータスライン装飾
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ウィンドウサイズ変更用プラグイン
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<C-U>'
  " 移動幅の設定
  let g:winresizer_vert_resize = 3
  let g:winresizer_horiz_resize = 1
'''

[[plugins]] # カラーテーブルを表示する
repo = 'guns/xterm-color-table.vim'

[[plugins]] # JavaScriptES6のシンタックス
repo = 'othree/yajs.vim'

[[plugins]] # vim上からgitコマンドを使えるプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]] # カッコやHTMLタグなどの挿入、削除、置換プラグイン
repo = 'tpope/vim-surround'

[[plugins]] # rails用プラグイン
repo = 'tpope/vim-rails'

[[plugins]] # vim help日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # インデントを可視化
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
  autocmd Colorscheme * highlight IndentGuidesOdd  ctermbg=235
  autocmd Colorscheme * highlight IndentGuidesEven ctermbg=236
'''

[[plugins]] # nerdtreeにアイコン表示
repo = 'ryanoasis/vim-devicons'

[[plugins]] # シンタックスエラーチェック
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_error = '✖︎'
  let g:ale_sign_warning = '⚠︎'
'''

[[plugins]] # 末尾の空白可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # gitで管理してる変更された箇所を行番号横に表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # surround.vimなどの変更を.で繰り返し可能にする
repo = 'tpope/vim-repeat'

[[plugins]] # ファイル検索プラグイン
repo = 'Shougo/denite.nvim'
hook_add = '''
  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR>
          \ denite#do_map('do_action')
    nnoremap <silent><buffer><expr> d
          \ denite#do_map('do_action', 'delete')
    nnoremap <silent><buffer><expr> p
          \ denite#do_map('do_action', 'preview')
    nnoremap <silent><buffer><expr> q
          \ denite#do_map('quit')
    nnoremap <silent><buffer><expr> i
          \ denite#do_map('open_filter_buffer')
    nnoremap <silent><buffer><expr> <Space>
          \ denite#do_map('toggle_select').'j'
  endfunction

  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])

  nnoremap <Space>f :<C-u>Denite file/rec<CR>
  nnoremap <Space>b :<C-u>Denite buffer<CR>
  nnoremap <Space>g :<C-u>Denite grep<CR>
'''


[[plugins]] # スクロールを滑らかに
repo = 'yuttie/comfortable-motion.vim'
hook_add = '''
  let g:comfortable_motion_friction = 800.0 " 摩擦力
  let g:comfortable_motion_air_drag = 3.0 " 空気抵抗
  let g:comfortable_motion_no_default_key_mappings = 1
  nnoremap <silent> <C-f> :call comfortable_motion#flick(300)<CR>
  nnoremap <silent> <C-b> :call comfortable_motion#flick(-300)<CR>
'''

[[plugins]] # 非同期補完
repo = 'Shougo/deoplete.nvim'
hook_add = '''
'''

[[plugins]] # coffeescriptシンタックス
repo = 'kchmck/vim-coffee-script'

[[plugins]] # gundoグラフ可視化
repo = 'sjl/gundo.vim'
hook_add = '''
  let g:gundo_prefer_python3 = 1 " python3で動作(デフォルトではpython2.4)
  nnoremap <F5> :GundoToggle<CR>
'''

[[plugins]] # markdownプレビュー
repo = 'iamcco/markdown-preview.vim'

[[plugins]] # tomlシンタックス
repo = 'cespare/vim-toml'

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

[[plugins]] # Vue.jsシンタックス
repo = 'posva/vim-vue'
hook_add = '''
  autocmd FileType vue syntax sync fromstart
'''

[[plugins]] # スニペット
repo = 'Shougo/neosnippet-snippets'
